[build]
target = 'x86_64-unknown-linux-gnu'
[target.aarch64-linux-android]
linker = '/home/lucien/Android/Sdk/ndk/30.0.15729638/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android24-clang'
rustflags = [
    '-L',
    '/home/lucien/wattcoin-mobile-temp/.cargo',
    '-Clink-arg=-landroid',
    '-Clink-arg=-llog',
    '-Clink-arg=-lOpenSLES',
]

[target.armv7-linux-androideabi]
linker = '/home/lucien/Android/Sdk/ndk/30.0.15729638/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi24-clang'
rustflags = [
    '-L',
    '/home/lucien/wattcoin-mobile-temp/.cargo',
    '-Clink-arg=-landroid',
    '-Clink-arg=-llog',
    '-Clink-arg=-lOpenSLES',
]

[target.i686-linux-android]
linker = '/home/lucien/Android/Sdk/ndk/30.0.15729638/toolchains/llvm/prebuilt/linux-x86_64/bin/i686-linux-android24-clang'
rustflags = [
    '-L',
    '/home/lucien/wattcoin-mobile-temp/.cargo',
    '-Clink-arg=-landroid',
    '-Clink-arg=-llog',
    '-Clink-arg=-lOpenSLES',
]

[target.x86_64-linux-android]
linker = '/home/lucien/Android/Sdk/ndk/30.0.15729638/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android24-clang'
rustflags = [
    '-L',
    '/home/lucien/wattcoin-mobile-temp/.cargo',
    '-Clink-arg=-landroid',
    '-Clink-arg=-llog',
    '-Clink-arg=-lOpenSLES',
]

[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"
rustflags = [
    "-C", "link-arg=-static",             # La massue : Force absolument TOUT en statique (y compris pthread)
    "-C", "link-arg=-static-libgcc",      # Confirme pour libgcc
    "-C", "link-arg=-static-libstdc++",   # Confirme pour libstdc++
    "-C", "link-arg=-lstdc++",            # Maintenant on peut l'appeler, il sera statique !
    "-C", "link-arg=-ladvapi32"
]
