[package]
name = "wattcoin-wallet"
version = "2.1.11"
description = "Un Super Wallet Cypherpunk"
authors = ["ohm"]
edition = "2021"

[lib]
name = "wattcoin_wallet_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2.0.0", features = [] }
tauri-plugin-opener = "2.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bip39 = { version = "2.0.0", features = ["french"] }
hex = "0.4.3"
rand = "0.8.5"
bitcoin = { version = "0.32.0", features = ["std", "base64", "rand"] }
aes-gcm = "0.10.3"
pbkdf2 = "0.12.2"
sha2 = "0.10.6"
reqwest = { version = "0.12", default-features = false, features = ["json", "socks", "rustls-tls"] }
curve25519-dalek = "4.1.2"
tokio = { version = "1", features = ["full"] }
pqc_kyber = "0.7.1"
arti-client = { version = "0.22.0", default-features = false, features = ["tokio", "rustls", "onion-service-client"] }
tor-rtcompat = { version = "0.22.0", default-features = false, features = ["tokio", "rustls"] }
once_cell = "1.19.0"
rusqlite = { version = "0.31.0", features = ["bundled"] }
dirs = "6.0.0"
chrono = { version = "0.4", features = ["serde"] }
unicode-normalization = "0.1"
base64 = "0.22.1"
tauri-plugin-barcode-scanner = "2.4.5"
