name: Build Windows Wallet

on:
  workflow_dispatch: 

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: Installation des dépendances Frontend
        working-directory: ./desktop-wallet
        run: npm install

      - name: Build Tauri App (Génération du .msi)
        uses: tauri-apps/tauri-action@v0
        with:
          projectPath: ./desktop-wallet
          args: ''

      - name: Upload l'installeur Windows
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: ./desktop-wallet/target/release/bundle/msi/*.msi